### ISSUE TITLE
Cannot use docker image

### ISSUE THREAD

**Issue by dscho15** [jeolpyeoni/StyleCineGAN#1]
Hello,

First of all amazing work,

I have trouble using the docker image, since I'm facing a circular opencv import and not being able to compile with Ninja. Could you perhaps explain explicitly how you run things when you are inside docker? 

BR

**Comment by dscho15** [comment]
Got it to work through:

conda install cuda-nvcc -c nvidia
conda install -c nvidia cuda-toolkit

**Comment by Inferencer** [comment]
Can I add to this by asking what cuda version is recommended, is it 11.4?
I followed the steps including the one above and ended up with 12.4 I think and just want to confirm before I sort the cuda errors out 
seems when i use 
conda install -c nvidia cuda-toolkit
it installs alot of stuff related to cuda 12.4 
and
conda install cuda-nvcc -c nvidia just upgrades from 11.4 to 12.4

regardless of would i do or path i set i get
```
(cine) C:\Users\Jack\StyleCineGAN>python main.py --img_path ./samples/0002268 --save_dir ./results

>>> Loading StyleGAN...
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    sg2      = load_stylegan2(opts.sg2_ckpt)
  File "C:\Users\Jack\StyleCineGAN\utils\model_utils.py", line 20, in load_stylegan2
    from models.stylegan2.model import Generator
  File "C:\Users\Jack\StyleCineGAN\models\stylegan2\model.py", line 7, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\Users\Jack\StyleCineGAN\models\stylegan2\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\Jack\StyleCineGAN\models\stylegan2\op\fused_act.py", line 9, in <module>
    fused = load(
  File "C:\Users\Jack\anaconda3\envs\cine\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\Jack\anaconda3\envs\cine\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Jack\anaconda3\envs\cine\lib\site-packages\torch\utils\cpp_extension.py", line 1800, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "C:\Users\Jack\anaconda3\envs\cine\lib\site-packages\torch\utils\cpp_extension.py", line 1887, in _prepare_ldflags
    extra_ldflags.append(f'/LIBPATH:{_join_cuda_home("lib", "x64")}')
  File "C:\Users\Jack\anaconda3\envs\cine\lib\site-packages\torch\utils\cpp_extension.py", line 2407, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

**Comment by jeolpyeoni** [comment]
We used Cuda version 11.6 to test in our environment, please consider trying this version. Thank you all for showing your interest in our work.
